local lpeg = require "lpeglabel"
local re = require "relabel"
local P, S, V, R, utfR = lpeg.P, lpeg.S, lpeg.V, lpeg.R, lpeg.utfR
  local EMPTY = P''
  local neg = function (pat)
   return P(1) - pat
  end
local regex = function (s)
	return re.compile(s)
end
local tk = function (s)
	return P(s) * V"SKIP_"^0
end
local EOF = P(-1)

  local ci =  function (s)
    local pat = P""
    for i = 1, #s do
      local ch = s:sub(i, i)
      local lower = ch:lower()
      local upper = ch:upper()
      if lower == upper then
       pat = pat * P(ch)
      else
       pat = pat * S(lower .. upper)
      end
    end
    return pat
  end

local grammar = {
	"start_",
    start_ = V"SKIP_"^0 *  V"acmeCompUnit",
	acmeCompUnit = (V"acmeImportDeclaration")^0 * (V"acmeSystemDeclaration" + V"acmeFamilyDeclaration" + V"acmeDesignDeclaration")^1 * V"EOF",
  acmeImportDeclaration = V"IMPORT" * (V"filename" + V"stringLiteral") * V"SEMICOLON",
  stringLiteral = V"STRING_LITERAL",
  filename = (tk(ci('$')) + tk(ci('%')))^-1 * V"IDENTIFIER" * ((tk(ci('.')) + tk(ci(':')) + tk(ci('-')) + tk(ci('+')) + tk(ci('\\')) + tk(ci('\\\\')) + tk(ci('/')) + tk(ci('$')) + tk(ci('%')))^1 * V"IDENTIFIER")^0,
  identifier = V"IDENTIFIER",
  codeLiteral = V"STRING_LITERAL",
  acmeFamilyDeclaration = (V"FAMILY" + V"STYLE") * V"identifier" * (V"SEMICOLON" + (V"ASSIGN" * V"acmeFamilyBody" * (V"SEMICOLON")^-1) + (V"EXTENDS" * V"acmeFamilyRef" * (V"COMMA" * V"acmeFamilyRef")^0 * (V"SEMICOLON" + (V"WITH" * V"acmeFamilyBody" * (V"SEMICOLON")^-1)))),
  acmeFamilyBody = V"LBRACE" * (((V"PUBLIC" + V"PRIVATE")^-1 * (V"FINAL" + V"ABSTRACT")^-1 * (V"acmePortTypeDeclaration" + V"acmeRoleTypeDeclaration" + V"acmeComponentTypeDeclaration" + V"acmeConnectorTypeDeclaration" + V"acmeGenericElementTypeDeclaration" + V"acmePropertyTypeDeclaration" + V"acmeGroupTypeDeclaration")) + V"acmeDesignAnalysisDeclaration" + V"designRule" + V"acmePortDeclaration" + V"acmeRoleDeclaration" + V"acmeComponentDeclaration" + V"acmeConnectorDeclaration" + V"acmePropertyDeclaration" + V"acmeGroupDeclaration" + V"acmeAttachmentDeclaration")^0 * V"RBRACE",
  acmeSystemDeclaration = V"SYSTEM" * V"identifier" * (V"COLON" * V"acmeFamilyRef" * (V"COMMA" * V"acmeFamilyRef")^0)^-1 * (V"SEMICOLON" + (V"ASSIGN" * ((V"acmeSystemBody" * (V"SEMICOLON")^-1) + (V"NEW" * V"acmeFamilyInstantiationRef" * (V"COMMA" * V"acmeFamilyInstantiationRef")^0 * (V"SEMICOLON" + (V"EXTENDED" * V"WITH" * V"acmeSystemBody" * (V"SEMICOLON")^-1)))))),
  acmeSystemBody = V"LBRACE" * (V"acmePropertyDeclaration" + V"acmeComponentDeclaration" + V"acmeConnectorDeclaration" + V"acmeAttachmentDeclaration" + V"acmeGroupDeclaration" + V"designRule")^0 * V"RBRACE",
  acmeDesignDeclaration = V"DESIGN",
  acmeComponentTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeComponentInstantiatedTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeConnectorTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeConnectorInstantiatedTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmePortTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmePortInstantiatedTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeGroupTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeGroupInstantiatedTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeRoleTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeRoleInstantiatedTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeViewTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeViewInstantiatedTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeFamilyRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeFamilyInstantiationRef = V"identifier",
  acmeElementTypeRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmePropertyTypeDeclarationRef = V"identifier" * (V"DOT" * V"identifier")^-1,
  acmeInstanceRef = V"IDENTIFIER" * (V"DOT" * V"IDENTIFIER")^0,
  acmeGenericElementTypeDeclaration = V"ELEMENT" * V"TYPE" * V"identifier" * (V"SEMICOLON" + (V"ASSIGN" * V"acmeGenericElementBody" * (V"SEMICOLON")^-1) + (V"EXTENDS" * V"acmeElementTypeRef" * (V"COMMA" * V"acmeElementTypeRef")^0 * (V"SEMICOLON" + (V"WITH" * V"acmeGenericElementBody" * (V"SEMICOLON")^-1)))),
  acmeGenericElementBody = V"LBRACE" * (V"acmePropertyDeclaration" + V"designRule")^0 * V"RBRACE",
  acmeGroupTypeDeclaration = V"GROUP" * V"TYPE" * V"identifier" * (V"SEMICOLON" + (V"ASSIGN" * V"acmeGroupBody" * (V"SEMICOLON")^-1) + (V"EXTENDS" * V"acmeGroupTypeRef" * (V"COMMA" * V"acmeGroupTypeRef")^0 * (V"SEMICOLON" + (V"WITH" * V"acmeGroupBody" * (V"SEMICOLON")^-1)))),
  acmeGroupDeclaration = V"GROUP" * V"identifier" * (V"COLON" * V"acmeGroupTypeRef" * (V"COMMA" * V"acmeGroupTypeRef")^0)^-1 * (V"SEMICOLON" + (V"ASSIGN" * ((V"acmeGroupBody" * (V"SEMICOLON")^-1) + (V"NEW" * V"acmeGroupInstantiatedTypeRef" * (V"COMMA" * V"acmeGroupInstantiatedTypeRef")^0 * (V"SEMICOLON" + (V"EXTENDED" * V"WITH" * V"acmeGroupBody" * (V"SEMICOLON")^-1)))))),
  acmeGroupBody = V"LBRACE" * (V"acmeMembersBlock" + V"acmePropertyDeclaration" + V"designRule")^0 * V"RBRACE",
  acmeMembersBlock = V"MEMBERS" * V"LBRACE" * (V"acmeInstanceRef" * (V"COMMA" * V"acmeInstanceRef")^0)^-1 * V"RBRACE" * V"FixedRepetition_0",
  acmePortTypeDeclaration = V"PORT" * V"TYPE" * V"identifier" * (V"SEMICOLON" + (V"ASSIGN" * V"acmePortBody" * (V"SEMICOLON")^-1) + (V"EXTENDS" * V"acmePortTypeRef" * (V"COMMA" * V"acmePortTypeRef")^0 * (V"SEMICOLON" + (V"WITH" * V"acmePortBody" * (V"SEMICOLON")^-1)))),
  acmePortDeclaration = V"PORT" * V"identifier" * (V"COLON" * V"acmePortTypeRef" * (V"COMMA" * V"acmePortTypeRef")^0)^-1 * ((V"ASSIGN" * ((V"acmePortBody" * (V"SEMICOLON")^-1) + (V"NEW" * V"acmePortInstantiatedTypeRef" * (V"COMMA" * V"acmePortInstantiatedTypeRef")^0 * (V"SEMICOLON" + (V"EXTENDED" * V"WITH" * V"acmePortBody" * (V"SEMICOLON")^-1))))) + (V"SEMICOLON")^-1),
  acmePortBody = V"LBRACE" * (V"acmePropertyDeclaration" + V"designRule" + V"acmeRepresentationDeclaration")^0 * V"RBRACE",
  acmeRoleTypeDeclaration = V"ROLE" * V"TYPE" * V"identifier" * (V"SEMICOLON" + (V"ASSIGN" * V"acmeRoleBody" * (V"SEMICOLON")^-1) + (V"EXTENDS" * V"acmeRoleTypeRef" * (V"COMMA" * V"acmeRoleTypeRef")^0 * (V"SEMICOLON" + (V"WITH" * V"acmeRoleBody" * (V"SEMICOLON")^-1)))),
  acmeRoleDeclaration = V"ROLE" * V"identifier" * (V"COLON" * V"acmeRoleTypeRef" * (V"COMMA" * V"acmeRoleTypeRef")^0)^-1 * (V"SEMICOLON" + (V"ASSIGN" * ((V"acmeRoleBody" * (V"SEMICOLON")^-1) + (V"NEW" * V"acmeRoleInstantiatedTypeRef" * (V"COMMA" * V"acmeRoleInstantiatedTypeRef")^0 * (V"SEMICOLON" + (V"EXTENDED" * V"WITH" * V"acmeRoleBody" * (V"SEMICOLON")^-1)))))),
  acmeRoleBody = V"LBRACE" * (V"acmePropertyDeclaration" + V"designRule" + V"acmeRepresentationDeclaration")^0 * V"RBRACE",
  acmeComponentTypeDeclaration = V"COMPONENT" * V"TYPE" * V"identifier" * (V"SEMICOLON" + (V"ASSIGN" * V"acmeComponentBody" * (V"SEMICOLON")^-1) + (V"EXTENDS" * V"acmeComponentTypeRef" * (V"COMMA" * V"acmeComponentTypeRef")^0 * (V"SEMICOLON" + (V"WITH" * V"acmeComponentBody" * (V"SEMICOLON")^-1)))),
  acmeComponentDeclaration = V"COMPONENT" * V"identifier" * (V"COLON" * V"acmeComponentTypeRef" * (V"COMMA" * V"acmeComponentTypeRef")^0)^-1 * (V"SEMICOLON" + (V"ASSIGN" * ((V"acmeComponentBody" * (V"SEMICOLON")^-1) + (V"NEW" * V"acmeComponentInstantiatedTypeRef" * (V"COMMA" * V"acmeComponentInstantiatedTypeRef")^0 * (V"SEMICOLON" + (V"EXTENDED" * V"WITH" * V"acmeComponentBody" * (V"SEMICOLON")^-1)))))),
  acmeComponentBody = V"LBRACE" * (V"acmePropertyDeclaration" + V"acmePortDeclaration" + V"designRule" + V"acmeRepresentationDeclaration")^0 * V"RBRACE",
  acmeConnectorTypeDeclaration = V"CONNECTOR" * V"TYPE" * V"identifier" * (V"SEMICOLON" + (V"ASSIGN" * V"acmeConnectorBody" * (V"SEMICOLON")^-1) + (V"EXTENDS" * V"acmeConnectorTypeRef" * (V"COMMA" * V"acmeConnectorTypeRef")^0 * (V"SEMICOLON" + (V"WITH" * V"acmeConnectorBody" * (V"SEMICOLON")^-1)))),
  acmeConnectorDeclaration = V"CONNECTOR" * V"identifier" * (V"COLON" * V"acmeConnectorTypeRef" * (V"COMMA" * V"acmeConnectorTypeRef")^0)^-1 * (V"SEMICOLON" + (V"ASSIGN" * ((V"acmeConnectorBody" * (V"SEMICOLON")^-1) + (V"NEW" * V"acmeConnectorInstantiatedTypeRef" * (V"COMMA" * V"acmeConnectorInstantiatedTypeRef")^0 * (V"SEMICOLON" + (V"EXTENDED" * V"WITH" * V"acmeConnectorBody" * (V"SEMICOLON")^-1)))))),
  acmeConnectorBody = V"LBRACE" * (V"acmePropertyDeclaration" + V"acmeRoleDeclaration" + V"designRule" + V"acmeRepresentationDeclaration")^0 * V"RBRACE",
  acmeRepresentationDeclaration = V"REPRESENTATION" * (V"IDENTIFIER" * V"ASSIGN")^-1 * V"LBRACE" * V"acmeSystemDeclaration" * (V"acmeBindingsMapDeclaration")^-1 * V"RBRACE" * V"FixedRepetition_1",
  acmeBindingsMapDeclaration = V"BINDINGS" * V"LBRACE" * (V"acmeBindingDeclaration")^0 * V"RBRACE" * (V"SEMICOLON")^-1,
  acmeBindingDeclaration = V"acmeInstanceRef" * V"TO" * V"acmeInstanceRef" * (V"LBRACE" * V"acmePropertyDeclaration" * V"acmePropertyBlock" * V"RBRACE")^-1 * V"SEMICOLON",
  acmeAttachmentDeclaration = V"ATTACHMENT" * V"acmeInstanceRef" * V"TO" * V"acmeInstanceRef" * V"SEMICOLON",
  acmePropertyDeclaration = V"PROPERTY" * V"identifier" * (V"COLON" * V"acmePropertyTypeRef")^-1 * ((V"ASSIGN" * V"acmePropertyValueDeclaration") + (V"CONTAINASSIGN" * V"acmePropertyValueDeclaration"))^-1 * (V"acmePropertyBlock")^-1 * V"SEMICOLON",
  acmePropertyValueDeclaration = V"INTEGER_LITERAL" + ((V"MINUS" + V"PLUS")^0 * V"FLOATING_POINT_LITERAL") + V"STRING_LITERAL" + V"FALSE" + V"TRUE" + V"acmePropertySet" + V"acmePropertyRecord" + V"acmePropertySequence" + V"enumidentifier",
  enumidentifier = V"IDENTIFIER",
  acmePropertyElement = (V"IDENTIFIER" * (tk(ci('.')) * V"IDENTIFIER")^0) + V"acmePropertyCompoundElement",
  acmePropertyCompoundElement = V"acmePropertySet" + V"acmePropertyRecord" + V"acmePropertySequence",
  acmePropertySet = V"LBRACE" * (V"acmePropertyValueDeclaration" * (V"COMMA" * V"acmePropertyValueDeclaration")^0)^-1 * V"RBRACE",
  acmePropertyRecordEntry = V"identifier" * (V"COLON" * V"acmePropertyTypeRef")^-1 * V"ASSIGN" * V"acmePropertyValueDeclaration",
  acmePropertyRecord = V"LBRACKET" * (V"acmePropertyRecordEntry" * (V"SEMICOLON" * V"acmePropertyRecordEntry")^0 * (V"SEMICOLON")^-1)^-1 * V"RBRACKET",
  acmePropertySequence = V"LANGLE" * (V"acmePropertyValueDeclaration" * (V"COMMA" * V"acmePropertyValueDeclaration")^0)^-1 * V"RANGLE",
  acmePropertyTypeRecord = V"RECORD" * V"LBRACKET" * (V"acmePropertyRecordFieldDescription")^0 * V"RBRACKET",
  acmePropertyTypeSet = V"SET" * V"LBRACE" * (V"acmeTypeRef")^-1 * V"RBRACE",
  acmePropertyTypeSequence = V"SEQUENCE" * V"LANGLE" * (V"acmePropertyTypeRef")^-1 * V"RANGLE",
  acmePropertyTypeEnum = V"ENUM" * V"LBRACE" * V"identifier" * (V"COMMA" * V"identifier")^0 * V"RBRACE",
  acmePropertyRecordFieldDescription = V"identifier" * V"COLON" * V"acmePropertyTypeRef" * V"SEMICOLON",
  acmePropertyTypeRef = V"acmePropertyTypeStructure" + V"acmePropertyTypeDeclarationRef",
  acmePropertyTypeStructure = V"acmePropertyTypeAny" + V"acmePropertyTypeInt" + V"acmePropertyTypeFloat" + V"acmePropertyTypeDouble" + V"acmePropertyTypeString" + V"acmePropertyTypeBoolean" + V"acmePropertyTypeRecord" + V"acmePropertyTypeSet" + V"acmePropertyTypeSequence" + V"acmePropertyTypeEnum",
  acmePropertyTypeDeclaration = V"PROPERTY" * V"TYPE" * V"identifier" * (V"SEMICOLON" + (V"ASSIGN" * (V"acmePropertyTypeInt" + V"acmePropertyTypeFloat" + V"acmePropertyTypeDouble" + V"acmePropertyTypeString" + V"acmePropertyTypeBoolean" + V"acmePropertyTypeRecord" + V"acmePropertyTypeSet" + V"acmePropertyTypeSequence" + V"acmePropertyTypeEnum" + V"acmePropertyTypeAny") * V"SEMICOLON")),
  acmePropertyBlockEntry = V"identifier" * (V"COLON" * V"acmePropertyTypeRef")^-1 * ((V"ASSIGN" * V"acmePropertyValueDeclaration") + (V"CONTAINASSIGN" * V"acmePropertyValueDeclaration"))^-1 * V"SEMICOLON",
  acmePropertyBlock = V"PROPBEGIN" * (V"acmePropertyBlockEntry")^1 * V"PROPEND",
  acmePropertyTypeInt = V"INT",
  acmePropertyTypeAny = V"ANY",
  acmePropertyTypeFloat = V"FLOAT",
  acmePropertyTypeDouble = V"DOUBLE",
  acmePropertyTypeString = V"STRING",
  acmePropertyTypeBoolean = V"boolean",
  acmeViewDeclaration = V"VIEW" * V"identifier" * (V"COLON" * V"acmeViewTypeRef")^-1 * (V"SEMICOLON" + (V"ASSIGN" * ((V"acmeViewBody" * (V"SEMICOLON")^-1) + (V"NEW" * V"acmeViewInstantiatedTypeRef" * (V"SEMICOLON" + (V"EXTENDED" * V"WITH" * V"acmeViewBody" * (V"SEMICOLON")^-1)))))),
  acmeViewTypeDeclaration = V"VIEW" * V"TYPE" * V"identifier" * (V"SEMICOLON" + (V"ASSIGN" * V"acmeViewBody" * (V"SEMICOLON")^-1) + (V"EXTENDS" * V"acmeViewTypeRef" * (V"SEMICOLON" + (V"WITH" * V"acmeViewBody" * (V"SEMICOLON")^-1)))),
  acmeViewBody = V"LBRACE" * V"RBRACE",
  designRule = (V"DESIGN")^-1 * (V"RULE" * V"IDENTIFIER" * (V"ASSIGN")^-1)^-1 * ((V"INVARIANT" * V"designRuleExpression") + (V"HEURISTIC" * V"designRuleExpression"))^-1 * (V"acmePropertyBlock")^-1 * V"SEMICOLON",
  acmeDesignAnalysisDeclaration = ((V"DESIGN")^-1 * V"ANALYSIS" * V"IDENTIFIER" * V"LPAREN" * (V"formalParam" * (V"COMMA" * V"formalParam")^0)^-1 * V"RPAREN" * V"COLON" * V"acmeTypeRef" * V"ASSIGN" * V"designRuleExpression" * (V"acmePropertyBlock")^-1 * V"SEMICOLON") + (V"EXTERNAL" * (V"DESIGN")^-1 * V"ANALYSIS" * V"IDENTIFIER" * V"LPAREN" * (V"formalParam" * (V"COMMA" * V"formalParam")^0)^-1 * V"RPAREN" * V"COLON" * V"acmeTypeRef" * V"ASSIGN" * (V"codeLiteral" + (V"identifier" * (V"DOT" * V"identifier")^0)) * V"SEMICOLON"),
  formalParam = V"identifier" * V"COLON" * V"acmeTypeRef",
  terminatedDesignRuleExpression = V"designRuleExpression" * V"SEMICOLON",
  designRuleExpression = V"aSTDRImpliesExpression" * V"FixedRepetition_2",
  aSTDRImpliesExpression = V"dRIffExpression" * V"FixedRepetition_3",
  dRIffExpression = V"dRAndExpression" * V"FixedRepetition_4",
  dRAndExpression = V"dRNegateExpression" * V"FixedRepetition_5",
  dRNegateExpression = (V"BANG" * V"dRNegateExpression") + V"dREqualityExpression",
  dREqualityExpression = V"dRRelationalExpression" * V"FixedRepetition_6",
  dRRelationalExpression = V"dRAdditiveExpression" * V"FixedRepetition_7",
  dRAdditiveExpression = V"dRMultiplicativeExpression" * V"FixedRepetition_8",
  dRMultiplicativeExpression = V"dRNegativeExpression" * V"FixedRepetition_9",
  dRNegativeExpression = (V"MINUS" * V"dRNegativeExpression") + V"primitiveExpression",
  primitiveExpression = V"literalConstant" + V"reference" + V"parentheticalExpression" + V"setExpression" + V"literalSequence" + V"literalRecord" + V"quantifiedExpression" + V"sequenceExpression",
  parentheticalExpression = V"LPAREN" * V"designRuleExpression" * V"RPAREN",
  reference = V"identifier" * (V"DOT" * (V"identifier" + V"setReference"))^0 * (V"actualParams")^-1,
  setReference = V"TYPE" + V"COMPONENTS" + V"CONNECTORS" + V"PORTS" + V"ROLES" + V"GROUPS" + V"MEMBERS" + V"PROPERTIES" + V"REPRESENTATIONS" + V"ATTACHEDPORTS" + V"ATTACHEDROLES",
  actualParams = V"LPAREN" * (V"designRuleExpression" * (V"COMMA" * V"designRuleExpression")^0)^-1 * V"RPAREN",
  literalConstant = V"INTEGER_LITERAL" + V"FLOATING_POINT_LITERAL" + V"STRING_LITERAL" + V"TRUE" + V"FALSE" + V"COMPONENT" + V"GROUP" + V"CONNECTOR" + V"PORT" + V"ROLE" + V"SYSTEM" + V"ELEMENT" + V"PROPERTY" + V"INT" + V"FLOAT" + V"DOUBLE" + V"STRING" + V"boolean" + V"ENUM" + V"SET" + V"SEQUENCE" + V"RECORD",
  quantifiedExpression = (V"FORALL" + (V"EXISTS" * (V"UNIQUE")^-1)) * V"variableSetDeclaration" * (V"COMMA" * V"variableSetDeclaration")^0 * V"BIT_OR" * V"designRuleExpression",
  distinctVariableSetDeclaration = V"DISTINCT" * V"identifier" * (V"COMMA" * V"identifier")^0 * ((V"COLON" + V"SET_DECLARE") * V"acmeTypeRef")^-1 * V"IN" * (V"setExpression" + V"reference"),
  variableSetDeclaration = V"distinctVariableSetDeclaration" + (V"identifier" * (V"COMMA" * V"identifier")^0 * ((V"COLON" + V"SET_DECLARE") * V"acmeTypeRef")^-1 * V"IN" * (V"setExpression" + V"reference")),
  sequenceExpression = V"LANGLE" * V"pathExpression" * V"RANGLE",
  setExpression = V"literalSet" + V"setConstructor" + V"pathExpression",
  pathExpression = V"SLASH" * V"reference" * ((V"COLON" + V"SET_DECLARE") * V"acmeTypeRef")^-1 * (V"LBRACKET" * V"designRuleExpression" * V"RBRACKET")^-1 * V"FixedRepetition_10",
  pathExpressionContinuation = (V"setReference" * ((V"COLON" + V"SET_DECLARE") * V"acmeTypeRef")^-1 * (V"LBRACKET" * V"designRuleExpression" * V"RBRACKET")^-1 * (V"SLASH" * V"pathExpressionContinuation")^0) + ((V"ELLIPSIS")^-1 * V"reference"),
  literalSet = (V"LBRACE" * V"RBRACE") + (V"LBRACE" * (V"literalConstant" + V"reference") * (V"COMMA" * (V"literalConstant" + V"reference"))^0 * V"RBRACE"),
  literalSequence = (V"LANGLE" * V"RANGLE") + (V"LANGLE" * (V"literalConstant" + V"reference") * (V"COMMA" * (V"literalConstant" + V"reference"))^0 * V"RANGLE"),
  literalRecordEntry = V"identifier" * (V"COLON" * V"acmePropertyTypeRef")^-1 * V"ASSIGN" * V"literalConstant",
  literalRecord = V"LBRACKET" * (V"literalRecordEntry" * (V"SEMICOLON" * V"literalRecordEntry")^0 * (V"SEMICOLON")^-1)^-1 * V"RBRACKET",
  setConstructor = ((V"LBRACE")^-1 * V"SELECT" * V"variableSetDeclaration" * V"BIT_OR" * V"designRuleExpression" * (V"RBRACE")^-1) + ((V"LBRACE")^-1 * V"COLLECT" * V"reference" * V"COLON" * V"acmeTypeRef" * V"IN" * (V"setExpression" + V"reference") * V"BIT_OR" * V"designRuleExpression" * (V"RBRACE")^-1),
  acmeTypeRef = V"SYSTEM" + V"COMPONENT" + V"GROUP" + V"CONNECTOR" + V"PORT" + V"ROLE" + V"PROPERTY" + V"ELEMENT" + V"TYPE" + V"REPRESENTATION" + V"reference" + V"acmePropertyTypeStructure",
  ABSTRACT = P(ci('abstract')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ANALYSIS = P(ci('analysis')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  AND = P(ci('and')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ANY = P(ci('any')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ASSIGN = P(ci('=')) * V"SKIP_"^0,
  ATTACHMENT = P(ci('attachment')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ATTACHMENTS = P(ci('attachments')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ATTACHEDPORTS = P(ci('attachedports')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ATTACHEDROLES = P(ci('attachedroles')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  BANG = P(ci('!')) * V"SKIP_"^0,
  BINDINGS = P(ci('bindings')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  COLON = P(ci(':')) * V"SKIP_"^0,
  COMMA = P(ci(',')) * V"SKIP_"^0,
  COLLECT = P(ci('collect')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  COMPONENT = P(ci('component')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  COMPONENTS = P(ci('components')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  CONNECTOR = P(ci('connector')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  CONTAINASSIGN = P(ci('containassign')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  CONNECTORS = P(ci('connectors')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  DESIGN = P(ci('design')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  DISTINCT = P(ci('distinct')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  DOT = P(ci('.')) * V"SKIP_"^0,
  DOUBLE = P(ci('double')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ELEMENT = P(ci('element')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ENUM = P(ci('enum')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  EXTENDED = P(ci('extended')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  EXTENDS = P(ci('extends')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  EXTERNAL = P(ci('external')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  EXISTS = P(ci('exists')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ELLIPSIS = P(ci('...')) * V"SKIP_"^0,
  EQ = P(ci('==')) * V"SKIP_"^0,
  FAMILY = P(ci('family')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  FINAL = P(ci('final')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  FORALL = P(ci('forall')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  FLOAT = P(ci('float')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  GROUP = P(ci('group')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  GROUPS = P(ci('groups')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  GE = P(ci('>=')) * V"SKIP_"^0,
  HEURISTIC = P(ci('heuristic')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  IFF = P(ci('<->')) * V"SKIP_"^0,
  IMPORT = P(ci('import')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  IN = P(ci('in')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  INT = P(ci('int')) + P(ci('integer')) * V"SKIP_"^0,
  INVARIANT = P(ci('invariant')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  IMPLIES = P(ci('->')) * V"SKIP_"^0,
  LBRACE = P(ci('{')) * V"SKIP_"^0,
  RBRACE = P(ci('}')) * V"SKIP_"^0,
  LBRACKET = P(ci('[')) * V"SKIP_"^0,
  RBRACKET = P(ci(']')) * V"SKIP_"^0,
  LPAREN = P(ci('(')) * V"SKIP_"^0,
  RPAREN = P(ci(')')) * V"SKIP_"^0,
  LANGLE = P(ci('<')) * V"SKIP_"^0,
  RANGLE = P(ci('>')) * V"SKIP_"^0,
  LE = P(ci('<=')) * V"SKIP_"^0,
  NE = P(ci('!=')) * V"SKIP_"^0,
  NEW = P(ci('new')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  MEMBERS = P(ci('members')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  MINUS = P(ci('-')) * V"SKIP_"^0,
  OR = P(ci('or')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  pathseparator = tk(ci('\\\\')) + tk(ci('\\')) + tk(ci('.')) + tk(ci(':')) + tk(ci('-')) + tk(ci('+')) + tk(ci('/')) + tk(ci('$')) + tk(ci('%')),
  PUBLIC = P(ci('public')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  PRIVATE = P(ci('private')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  POWER = P(ci('power')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  PLUS = P(ci('+')) * V"SKIP_"^0,
  PORT = P(ci('port')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  PORTS = P(ci('ports')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  PROPERTY = P(ci('property')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  PROPERTIES = P(ci('properties')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  PROPBEGIN = P(ci('<<')) * V"SKIP_"^0,
  PROPEND = P(ci('>>')) * V"SKIP_"^0,
  RECORD = P(ci('record')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  REPRESENTATION = P(ci('representation')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  REM = P(ci('%')) * V"SKIP_"^0,
  REPRESENTATIONS = P(ci('representations')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ROLE = P(ci('role')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  RULE = P(ci('rule')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  ROLES = P(ci('roles')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  SEQUENCE = P(ci('sequence')) + P(ci('seq')) * V"SKIP_"^0,
  SELECT = P(ci('select')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  SEMICOLON = P(ci(';')) * V"SKIP_"^0,
  SET = P(ci('set')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  SET_DECLARE = P(ci(':!')) * V"SKIP_"^0,
  SLASH = P(ci('/')) * V"SKIP_"^0,
  STAR = P(ci('*')) * V"SKIP_"^0,
  STRING = P(ci('string')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  STYLE = P(ci('style')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  SYSTEM = P(ci('system')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  TO = P(ci('to')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  TYPE = P(ci('type')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  UNIQUE = P(ci('unique')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  WITH = P(ci('with')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  VIEW = P(ci('view')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  BIT_OR = P(ci('|')) * V"SKIP_"^0,
  TRUE = P(ci('true')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  FALSE = P(ci('false')) * -((R('az') + R('AZ') + R('09') + P('_'))) * V"SKIP_"^0,
  boolean = V"TRUE" + V"FALSE",
  FLOATING_POINT_LITERAL = ((R('09')))^1 * P(ci('.')) * ((R('09')))^1 * V"SKIP_"^0,
  INTEGER_LITERAL = ((R('09')))^1 * V"SKIP_"^0,
  STRING_LITERAL = P(ci('"')) * neg(P(ci('"'))) * P(ci('"')) * V"SKIP_"^0,
  IDENTIFIER = -(P(ci('representations')) + P(ci('representation')) + P(ci('attachedports')) + P(ci('containassign')) + P(ci('attachedroles')) + P(ci('attachments')) + P(ci('components')) + P(ci('properties')) + P(ci('connectors')) + P(ci('attachment')) + P(ci('heuristic')) + P(ci('component')) + P(ci('invariant')) + P(ci('connector')) + P(ci('external')) + P(ci('property')) + P(ci('analysis')) + P(ci('distinct')) + P(ci('bindings')) + P(ci('abstract')) + P(ci('extended')) + P(ci('sequence')) + P(ci('collect')) + P(ci('extends')) + P(ci('integer')) + P(ci('element')) + P(ci('members')) + P(ci('private')) + P(ci('import')) + P(ci('groups')) + P(ci('string')) + P(ci('forall')) + P(ci('public')) + P(ci('select')) + P(ci('exists')) + P(ci('double')) + P(ci('record')) + P(ci('design')) + P(ci('unique')) + P(ci('system')) + P(ci('family')) + P(ci('style')) + P(ci('roles')) + P(ci('power')) + P(ci('group')) + P(ci('ports')) + P(ci('final')) + P(ci('false')) + P(ci('float')) + P(ci('with')) + P(ci('port')) + P(ci('role')) + P(ci('enum')) + P(ci('true')) + P(ci('type')) + P(ci('view')) + P(ci('rule')) + P(ci('and')) + P(ci('seq')) + P(ci('any')) + P(ci('int')) + P(ci('new')) + P(ci('set')) + P(ci('in')) + P(ci('or')) + P(ci('to'))) * (R('az') + R('AZ')) * ((R('az') + R('AZ') + R('09') + P('_') + P('-')))^0 * V"SKIP_"^0,
  LINE_COMMENT = P(ci('//')) * (neg((P('\r') + P('\n'))))^0 * V"SKIP_"^0,
  BLOCK_COMMENT = P(ci('/*')) * neg(P(ci('*/'))) * P(ci('*/')) * V"SKIP_"^0,
  WS = ((P(' ') + P('\r') + P('\n') + P('\t')))^1 * V"SKIP_"^0,
  FixedRepetition_0 = (V"SEMICOLON" * #(V"HEURISTIC" + V"DESIGN" + V"MEMBERS" + V"PROPBEGIN" + V"RBRACE" + V"PROPERTY" + V"SEMICOLON" + V"INVARIANT" + V"RULE")) + EMPTY,
  FixedRepetition_1 = (V"SEMICOLON" * #(V"ROLE" + V"HEURISTIC" + V"DESIGN" + V"PROPBEGIN" + V"RBRACE" + V"PORT" + V"PROPERTY" + V"SEMICOLON" + V"INVARIANT" + V"REPRESENTATION" + V"RULE")) + EMPTY,
  FixedRepetition_2 = ((V"OR" * V"aSTDRImpliesExpression") * V"FixedRepetition_2") + #(V"COMMA" + V"IMPLIES" + V"OR" + V"RANGLE" + V"SLASH" + V"IFF" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"MINUS" + V"LANGLE" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"NE" + V"AND" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS"),
  FixedRepetition_3 = ((V"IMPLIES" * V"dRIffExpression") * V"FixedRepetition_3") + #(V"COMMA" + V"IMPLIES" + V"OR" + V"RANGLE" + V"SLASH" + V"IFF" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"MINUS" + V"LANGLE" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"NE" + V"AND" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS"),
  FixedRepetition_4 = ((V"IFF" * V"dRAndExpression") * V"FixedRepetition_4") + #(V"IMPLIES" + V"COMMA" + V"OR" + V"RANGLE" + V"SLASH" + V"IFF" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"MINUS" + V"LANGLE" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"NE" + V"AND" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS"),
  FixedRepetition_5 = ((V"AND" * V"dRNegateExpression") * V"FixedRepetition_5") + #(V"IMPLIES" + V"COMMA" + V"OR" + V"RANGLE" + V"IFF" + V"SLASH" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"MINUS" + V"LANGLE" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"NE" + V"AND" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS"),
  FixedRepetition_6 = (((V"EQ" * V"dRRelationalExpression") + (V"NE" * V"dRRelationalExpression")) * V"FixedRepetition_6") + #(V"IMPLIES" + V"COMMA" + V"OR" + V"RANGLE" + V"IFF" + V"SLASH" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"MINUS" + V"LANGLE" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"AND" + V"NE" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS"),
  FixedRepetition_7 = (((V"LANGLE" * V"dRAdditiveExpression") + (V"RANGLE" * V"dRAdditiveExpression") + (V"LE" * V"dRAdditiveExpression") + (V"GE" * V"dRAdditiveExpression")) * V"FixedRepetition_7") + #(V"IMPLIES" + V"COMMA" + V"OR" + V"RANGLE" + V"IFF" + V"SLASH" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"MINUS" + V"LANGLE" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"NE" + V"AND" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS"),
  FixedRepetition_8 = (((V"PLUS" * V"dRMultiplicativeExpression") + (V"MINUS" * V"dRMultiplicativeExpression")) * V"FixedRepetition_8") + #(V"IMPLIES" + V"COMMA" + V"OR" + V"RANGLE" + V"IFF" + V"SLASH" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"LANGLE" + V"MINUS" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"NE" + V"AND" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS"),
  FixedRepetition_9 = (((V"STAR" * V"dRNegativeExpression") + (V"SLASH" * V"dRNegativeExpression") + (V"REM" * V"dRNegativeExpression") + (V"POWER" * V"dRNegativeExpression")) * V"FixedRepetition_9") + #(V"IMPLIES" + V"COMMA" + V"OR" + V"RANGLE" + V"IFF" + V"SLASH" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"MINUS" + V"LANGLE" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"NE" + V"AND" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS"),
  FixedRepetition_10 = ((V"SLASH" * V"pathExpressionContinuation") * V"FixedRepetition_10") + #(V"IMPLIES" + V"COMMA" + V"OR" + V"RANGLE" + V"SLASH" + V"IFF" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"MINUS" + V"LANGLE" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"NE" + V"AND" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS"),
  FixedRepetition_11 = (V"RBRACE" * #(V"IMPLIES" + V"COMMA" + V"OR" + V"RANGLE" + V"SLASH" + V"IFF" + V"POWER" + V"RBRACKET" + V"RPAREN" + V"EQ" + V"MINUS" + V"LANGLE" + V"PROPBEGIN" + V"STAR" + V"RBRACE" + V"SEMICOLON" + V"NE" + V"AND" + V"LE" + V"BIT_OR" + V"REM" + V"GE" + V"PLUS")) + EMPTY,
  SKIP_ = (V"LINE_COMMENT" + V"BLOCK_COMMENT" + V"WS")^1,
	EOF = EOF,
    EMPTY = EMPTY,
    KEYWORDS = P'=' + P'!' + P':' + P',' + P'.' + P'...' + P'==' + P'>=' + P'<->' + P'->' + P'{' + P'}' + P'[' + P']' + P'(' + P')' + P'<' + P'>' + P'<=' + P'!=' + P'-' + P'+' + P'<<' + P'>>' + P'%' + P';' + P':!' + P'/' + P'*' + P'|',
}

local parse = function (input)
	local result, label, errpos = lpeg.match(grammar, input)
	if result then
		print("Parsed: ", result)
	else
      local line, col = re.calcline(input, errpos)
		print("LPEG Parsing failed at " .. line .. ":" .. col)
		os.exit(1)
	end
	return lpeg.match(grammar, input)
end

local input = io.read("*a")
print(parse(input))
